In [1]:
import pandas as pd

In [3]:
Data = pd.read_csv('Resources/mainDS.csv')

1.Display top 5 rows of the data

In [4]:
Data.head()

,ID,Loan Amount,Funded Amount,Funded Amount Investor,Term,Batch Enrolled,Interest Rate,Grade,Sub Grade,Home Ownership,...,Recoveries,Collection Recovery Fee,Collection 12 months Medical,Application Type,Last week Pay,Accounts Delinquent,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
0,65087372,10000,32236,12329.36286,59,BAT2522922,11.135007,B,C4,MORTGAGE,...,2.498291,0.793724,0,INDIVIDUAL,49,0,31,311301,6619,0
1,1450153,3609,11940,12191.99692,59,BAT1586599,12.237563,C,D3,RENT,...,2.377215,0.974821,0,INDIVIDUAL,109,0,53,182610,20885,0
2,1969101,28276,9311,21603.22455,59,BAT2136391,12.545884,F,D4,MORTGAGE,...,4.316277,1.020075,0,INDIVIDUAL,66,0,34,89801,26155,0
3,6651430,11170,6954,17877.15585,59,BAT2428731,16.731201,C,C3,MORTGAGE,...,0.107020,0.749971,0,INDIVIDUAL,39,0,40,9189,60214,0
4,14354669,16890,13226,13539.92667,59,BAT5341619,15.008300,C,D4,MORTGAGE,...,1294.818751,0.368953,0,INDIVIDUAL,18,0,430,126029,22579,0

2.Display last 5 rows of the data

In [5]:
Data.tail()

,ID,Loan Amount,Funded Amount,Funded Amount Investor,Term,Batch Enrolled,Interest Rate,Grade,Sub Grade,Home Ownership,...,Recoveries,Collection Recovery Fee,Collection 12 months Medical,Application Type,Last week Pay,Accounts Delinquent,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
70361,11093542,13154,22653,21804.279580,59,BAT1780517,10.722019,C,E2,RENT,...,0.500543,1.278989,0,INDIVIDUAL,38,0,40,63405,5524,0
70362,8055469,13791,9209,22065.647720,59,BAT1780517,14.075933,B,E5,MORTGAGE,...,3.290785,0.375653,0,INDIVIDUAL,89,0,29,132166,135755,0
70363,2142145,15299,9594,21500.619710,59,BAT5547201,10.668933,C,B4,RENT,...,1.881125,0.502448,0,INDIVIDUAL,107,0,46,8203,61245,0
70364,10342473,21608,5981,9952.213204,59,BAT4722912,9.549941,A,A2,MORTGAGE,...,0.470865,0.133257,0,INDIVIDUAL,14,0,59,100082,14706,0
70365,13613348,10517,20843,33559.365730,59,BAT1780517,9.188369,C,C3,MORTGAGE,...,975.186013,0.687089,0,INDIVIDUAL,32,0,373,293423,5666,0

3.Shape of the data

In [6]:
Data.shape

(70366, 35)

In [7]:
print('Number of rows', Data.shape[0])
print('Number of columns', Data.shape[1])

Number of rows 70366
Number of columns 35

4.Get Information of the data set

In [8]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70366 entries, 0 to 70365
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            70366 non-null  int64
 1   Loan Amount                   70366 non-null  int64
 2   Funded Amount                 70366 non-null  int64
 3   Funded Amount Investor        70366 non-null  float64
 4   Term                          70366 non-null  int64
 5   Batch Enrolled                70366 non-null  object
 6   Interest Rate                 70366 non-null  float64
 7   Grade                         70366 non-null  object
 8   Sub Grade                     70366 non-null  object
 9   Home Ownership                70366 non-null  object
 10  Employment Duration (years)   70366 non-null  int64
 11  Verification Status           70366 non-null  object
 12  Payment Plan                  70366 non-null  object
 13  Loan Title                    70366 non-null  object
 14  Debit to Income               70366 non-null  float64
 15  Delinquency - two years       70366 non-null  int64
 16  Inquires - six months         70366 non-null  int64
 17  Open Account                  70366 non-null  int64
 18  Public Record                 70366 non-null  int64
 19  Revolving Balance             70366 non-null  int64
 20  Revolving Utilities           70366 non-null  float64
 21  Total Accounts                70366 non-null  int64
 22  Initial List Status           70366 non-null  object
 23  Total Received Interest       70366 non-null  float64
 24  Total Received Late Fee       70366 non-null  float64
 25  Recoveries                    70366 non-null  float64
 26  Collection Recovery Fee       70366 non-null  float64
 27  Collection 12 months Medical  70366 non-null  int64
 28  Application Type              70366 non-null  object
 29  Last week Pay                 70366 non-null  int64
 30  Accounts Delinquent           70366 non-null  int64
 31  Total Collection Amount       70366 non-null  int64
 32  Total Current Balance         70366 non-null  int64
 33  Total Revolving Credit Limit  70366 non-null  int64
 34  Loan Status                   70366 non-null  int64
dtypes: float64(8), int64(18), object(9)
memory usage: 18.8+ MB

In [9]:
# List of columns to remove for loan default prediction
columns_to_remove = ['ID', 'Funded Amount', 'Funded Amount Investor', 'Term',
                     'Batch Enrolled', 'Grade', 'Sub Grade', 'Payment Plan',
                     'Loan Title', 'Public Record', 'Collection 12 months Medical',
                     'Application Type', 'Last week Pay', 'Accounts Delinquent']

df_clean = Data.drop(columns=columns_to_remove)

In [10]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70366 entries, 0 to 70365
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Loan Amount                   70366 non-null  int64
 1   Interest Rate                 70366 non-null  float64
 2   Home Ownership                70366 non-null  object
 3   Employment Duration (years)   70366 non-null  int64
 4   Verification Status           70366 non-null  object
 5   Debit to Income               70366 non-null  float64
 6   Delinquency - two years       70366 non-null  int64
 7   Inquires - six months         70366 non-null  int64
 8   Open Account                  70366 non-null  int64
 9   Revolving Balance             70366 non-null  int64
 10  Revolving Utilities           70366 non-null  float64
 11  Total Accounts                70366 non-null  int64
 12  Initial List Status           70366 non-null  object
 13  Total Received Interest       70366 non-null  float64
 14  Total Received Late Fee       70366 non-null  float64
 15  Recoveries                    70366 non-null  float64
 16  Collection Recovery Fee       70366 non-null  float64
 17  Total Collection Amount       70366 non-null  int64
 18  Total Current Balance         70366 non-null  int64
 19  Total Revolving Credit Limit  70366 non-null  int64
 20  Loan Status                   70366 non-null  int64
dtypes: float64(7), int64(11), object(3)
memory usage: 11.3+ MB

5.Handling catagorical columns

In [11]:
df_clean.sample(5)

,Loan Amount,Interest Rate,Home Ownership,Employment Duration (years),Verification Status,Debit to Income,Delinquency - two years,Inquires - six months,Open Account,Revolving Balance,...,Total Accounts,Initial List Status,Total Received Interest,Total Received Late Fee,Recoveries,Collection Recovery Fee,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
21833,23574,9.438589,RENT,4,Source Verified,27.304690,1,0,13,1518,...,19,w,1275.893934,0.061000,2.539782,0.758899,20,20178,1056,0
62092,17571,10.754002,RENT,6,Source Verified,21.337727,1,0,21,1285,...,18,w,1079.357814,31.546643,4.553757,0.309733,559,130814,12753,0
68395,8435,15.169186,MORTGAGE,5,Source Verified,18.231239,2,0,9,1859,...,8,w,650.224743,0.087759,0.663706,1.075883,2,84072,3589,0
19470,15302,11.523209,RENT,11,Verified,17.088345,0,0,14,9802,...,23,f,472.864697,0.008908,5.018187,1.197820,48,89593,39190,0
39620,5505,9.807434,RENT,9,Verified,15.255327,0,0,10,1443,...,30,w,2104.672395,0.048869,6.070411,1.081010,3208,50216,19052,0

In [12]:
# Data encoding
df_clean['Home Ownership'] = df_clean['Home Ownership'].map({'MORTGAGE': 1, 'RENT': 2, 'OWN': 3}).astype('int')
df_clean["Verification Status"] = df_clean["Verification Status"].map({"Not Verified": 1, "Source Verified": 2, "Verified": 3}).astype('int')
df_clean["Initial List Status"] = df_clean["Initial List Status"].map({"w": 1, "f": 2}).astype('int')

print("Current shape of dataset:", df_clean.shape)

Current shape of dataset: (70366, 21)

In [13]:
df_clean.sample(5)

,Loan Amount,Interest Rate,Home Ownership,Employment Duration (years),Verification Status,Debit to Income,Delinquency - two years,Inquires - six months,Open Account,Revolving Balance,...,Total Accounts,Initial List Status,Total Received Interest,Total Received Late Fee,Recoveries,Collection Recovery Fee,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
66145,26752,10.964796,1,8,2,28.967317,0,0,9,4311,...,36,2,1220.496976,0.079330,2.246306,1.462682,53,313883,13247,1
51587,31634,10.517007,1,5,3,12.042521,0,0,14,51,...,5,1,4448.507041,0.057033,4.824919,0.711675,21,207625,34749,0
45499,26809,15.250522,2,7,2,20.709742,1,0,11,1289,...,28,2,76.971741,0.007724,8.559834,0.379559,33,44518,26538,1
40607,19505,10.317222,1,2,1,6.356061,1,0,13,2222,...,39,2,854.375094,0.025665,4.460297,0.212449,6,92454,8214,0
46039,10533,13.672209,1,6,2,19.895391,0,0,11,5784,...,17,1,184.711734,0.031986,6.382979,0.468160,13,326453,5471,0

7.Store feauture matrix in X and response in y

In [14]:
X = df_clean.drop('Loan Status', axis = 1)
y = df_clean['Loan Status']

8.Feature scaling

In [15]:
df_clean.head()

,Loan Amount,Interest Rate,Home Ownership,Employment Duration (years),Verification Status,Debit to Income,Delinquency - two years,Inquires - six months,Open Account,Revolving Balance,...,Total Accounts,Initial List Status,Total Received Interest,Total Received Late Fee,Recoveries,Collection Recovery Fee,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
0,10000,11.135007,1,20,1,16.284758,1,0,13,24246,...,7,1,2929.646315,0.102055,2.498291,0.793724,31,311301,6619,0
1,3609,12.237563,2,4,2,15.412409,0,0,12,812,...,13,2,772.769385,0.036181,2.377215,0.974821,53,182610,20885,0
2,28276,12.545884,1,10,2,28.137619,0,0,14,1843,...,20,1,863.324396,18.778660,4.316277,1.020075,34,89801,26155,0
3,11170,16.731201,1,12,2,18.043730,1,0,7,13819,...,12,1,288.173196,0.044131,0.107020,0.749971,40,9189,60214,0
4,16890,15.008300,1,5,2,17.209886,1,3,13,1544,...,22,1,129.239553,19.306646,1294.818751,0.368953,430,126029,22579,0

In [16]:
cols = ['Loan Amount', 'Interest Rate', 'Employment Duration (years)', 'Debit to Income', 
        'Open Account', 'Revolving Balance', 'Total Accounts', 'Total Received Interest', 'Total Received Late Fee', 
        'Recoveries', 'Collection Recovery Fee', 'Total Collection Amount', 'Total Current Balance', 'Total Revolving Credit Limit']

In [17]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
X[cols]=st.fit_transform(X[cols])

In [18]:
X

,Loan Amount,Interest Rate,Home Ownership,Employment Duration (years),Verification Status,Debit to Income,Delinquency - two years,Inquires - six months,Open Account,Revolving Balance,Revolving Utilities,Total Accounts,Initial List Status,Total Received Interest,Total Received Late Fee,Recoveries,Collection Recovery Fee,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit
0,-0.818578,-0.189992,1,2.194195,1,-0.831962,1,0,-0.203901,2.120873,74.932551,-1.397865,1,0.388844,-0.198673,-0.160015,-0.095255,-0.155124,1.089633,-0.789679
1,-1.582950,0.106512,2,-0.911469,2,-0.935305,0,0,-0.364572,-0.879700,78.297186,-0.676552,2,-0.583453,-0.211236,-0.160355,-0.043399,-0.125608,0.164502,-0.108147
2,1.367254,0.189427,1,0.253155,2,0.572204,0,0,-0.043231,-0.747687,2.073040,0.164981,1,-0.542632,3.363209,-0.154910,-0.030441,-0.151099,-0.502682,0.143618
3,-0.678645,1.314963,1,0.641363,2,-0.623583,1,0,-1.167924,0.785762,67.467951,-0.796770,1,-0.801904,-0.209720,-0.166729,-0.107783,-0.143049,-1.082184,1.770726
4,0.005474,0.851632,1,-0.717365,2,-0.722365,1,3,-0.203901,-0.785972,85.250761,0.405419,1,-0.873550,3.463904,3.468632,-0.216885,0.380203,-0.242246,-0.027219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70361,-0.441356,-0.301055,2,-0.911469,2,0.525458,0,0,-0.525242,1.274377,78.841002,-0.556333,2,0.227739,-0.213020,-0.165624,0.043698,-0.143049,-0.692437,-0.841991
70362,-0.365170,0.600895,1,-0.717365,1,0.833821,0,0,-0.203901,2.073497,49.880686,0.285200,1,-0.850420,4.889302,-0.157789,-0.214967,-0.157808,-0.198129,5.379563
70363,-0.184811,-0.315331,2,-1.299677,2,1.045079,0,0,1.884814,0.660024,49.782126,-0.676552,2,-0.416925,-0.211001,-0.161748,-0.178660,-0.134999,-1.089272,1.819980
70364,0.569753,-0.616256,1,0.447259,2,1.376640,0,0,-0.685912,-0.499923,4.683398,-1.277646,1,-0.140971,-0.210372,-0.165707,-0.284375,-0.117558,-0.428774,-0.403337
70365,-0.756744,-0.713492,1,-1.105573,2,-0.669540,0,0,2.848837,0.686529,54.527422,0.886295,2,1.168678,-0.212890,2.571150,-0.125789,0.303727,0.961112,-0.835207

9.Splitting the data into test and training model

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
import numpy as np

In [20]:
model_df = {}
def model_val(model,X,y):
    X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                     test_size = 0.20,
                                                     random_state =42)
    
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print(f"{model} acuracy is {accuracy_score(y_test,y_pred)}")

    score = cross_val_score(model,X,y,cv = 5)
    print(f"{model} Avg corss val score is {np.mean(score)}")
    model_df[model] = round(np.mean(score)*100,2)

10.Logistic regression

In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model_val(model,X,y)

LogisticRegression() acuracy is 0.9135284922552224
LogisticRegression() Avg corss val score is 0.9113065976721939

12.Decision tree classifier

In [22]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model_val(model,X,y)

DecisionTreeClassifier() acuracy is 0.8222964331391218
DecisionTreeClassifier() Avg corss val score is 0.8235511424770943

13.Random forest classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model_val(model,X,y)

RandomForestClassifier() acuracy is 0.9135284922552224
RandomForestClassifier() Avg corss val score is 0.9112923870710855

14.Gradient boosting classifier

In [24]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
model_val(model,X,y)

GradientBoostingClassifier() acuracy is 0.9133863862441381
GradientBoostingClassifier() Avg corss val score is 0.9112355406275411

15.Hyperparameter tunning

In [25]:
from sklearn.model_selection import RandomizedSearchCV

Logistic regression

In [26]:
log_reg_grid = {"C":np.logspace(-4,4,20),
                "solver":['liblinear']}

In [27]:
rs_log_reg = RandomizedSearchCV(LogisticRegression(),
                   param_distributions = log_reg_grid,
                   n_iter = 20, cv = 5, verbose = True)

In [28]:
rs_log_reg.fit(X,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                                        'solver': ['liblinear']},
                   verbose=True)

In [29]:
rs_log_reg.best_score_

0.9113065976721939

In [30]:
rs_log_reg.best_params_

{'solver': 'liblinear', 'C': 0.0001}

Random forest classifier

In [31]:
RandomForestClassifier()

RandomForestClassifier()

In [32]:
rf_grid = {'n_estimators': np.arange(10,100,10),
'max_features' : ['auto', 'sqrt'],
'max_depth' : [None,10,20],
'min_samples_split' : [2,100],
'min_samples_leaf' : [1,5] }

In [33]:
rs_rf = RandomizedSearchCV(RandomForestClassifier(),
                            param_distributions=rf_grid,
                            cv=5,
                            n_iter=10,
                            n_jobs=-1,
                            verbose=True)

In [34]:
rs_rf.fit(X,y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'max_depth': [None, 10, 20],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 5],
                                        'min_samples_split': [2, 100],
                                        'n_estimators': array([10, 20, 30, 40, 50, 60, 70, 80, 90])},
                   verbose=True)

In [35]:
rs_rf.best_score_

0.9113065976721939

In [36]:
rs_rf.best_params_

{'n_estimators': 60,
 'min_samples_split': 100,
 'min_samples_leaf': 5,
 'max_features': 'sqrt',
 'max_depth': 20}

Logistic regression score before hyperparameters tunning = 0.9113065976721939

Logistic regression score after hyperparameters tunning = 0.9113065976721939

________

Random forest classifier score before hyperparameters tunning = 0.9112923870710855

Random forest classifier score after hyperparameters tunning = 0.9113065976721939

Save the model 

saving the model of random forest classifier which can be changed as per needs

In [37]:
X = df_clean.drop('Loan Status', axis = 1)
y = df_clean['Loan Status']

In [38]:
rf = RandomForestClassifier(n_estimators = 20,
 min_samples_split = 2,
 min_samples_leaf = 5,
 max_features = 'auto',
 max_depth = None)

In [39]:
rf.fit(X,y)

c:\Users\Ryzen\anaconda3\envs\dev\lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(

RandomForestClassifier(max_features='auto', min_samples_leaf=5, n_estimators=20)

In [40]:
import joblib

In [41]:
joblib.dump(rf, 'loan_status_prediction')

['loan_status_prediction']